[project]
name = "material-hasher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "vict0rsch", email = "victor.schmidt@entalpic.ai" }]
requires-python = ">=3.10"
dependencies = [
    "pymatgen>=2024.11.13",
    "structuregraph-helpers>=0.0.9",
    "fairchem-core==1.4.0",
    "torch_geometric>=2.4.0",
    "average-minimum-distance>=1.5.3",
    "datasets>=3.2.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipython>=8.29.0",
    "pre-commit>=4.0.1",
    "ruff>=0.8.0",
    "shibuya>=2024.10.15",
    "sphinx-autoapi>=3.3.2",
    "sphinx-autodoc-typehints>=2.5.0",
    "sphinx-code-include>=1.4.0",
    "sphinx-copybutton>=0.5.2",
    "sphinx-design>=0.6.1",
    "sphinx-math-dollar>=1.2.1",
    "sphinxawesome-theme>=5.3.2",
]
